/* config-breeze.h. Generated by cmake from config-breeze.h.cmake */

/*
    SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>

    SPDX-License-Identifier: GPL-2.0-or-later
*/

#ifndef config_oxygen_h
#define config_oxygen_h

/* Define to 1 if XCB libraries are found */
#cmakedefine01 OXYGEN_HAVE_X11

#endif
