# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt5']
   'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/frameworkintegration': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'

 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/frameworkintegration': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kcodecs': 'Frameworks/6.24'
    'frameworks/kcompletion': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'plasma/kdecoration': '@same'
    'plasma/libplasma': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
