# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/frameworkintegration': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/frameworkintegration': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'plasma/kdecoration': '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']

