{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "The Oxygen Project",
                "Name[bg]": "Екипът на Oxygen",
                "Name[ca@valencia]": "El projecte Oxygen",
                "Name[es]": "El proyecto Oxygen",
                "Name[eu]": "Oxygen proiektua",
                "Name[gl]": "Proxecto Oxygen",
                "Name[he]": "מיזם חמצן",
                "Name[nl]": "Het project Oxygen",
                "Name[sl]": "Projekt Oxygen",
                "Name[sv]": "Oxygen-projektet",
                "Name[tr]": "Oksijen Projesi",
                "Name[uk]": "Проєкт Oxygen",
                "Name[x-test]": "xxThe Oxygen Projectxx"
            }
        ],
        "Category": "",
        "Description": "Theme done in the Oxygen style",
        "Description[bg]": "Тема в стил Oxygen",
        "Description[ca@valencia]": "Tema fet en l'estil Oxygen",
        "Description[ca]": "Tema fet en l'estil Oxygen",
        "Description[es]": "Tema creado con el estilo de Oxígeno",
        "Description[eu]": "Oxygen-en estilora egindako gaia",
        "Description[gl]": "Tema feito no estilo Oxygen.",
        "Description[he]": "ערכת העיצוב ",
        "Description[ka]": "Oxygen-ის სტილში შესრულებული თემა",
        "Description[nl]": "Thema in Oxygen-stijl",
        "Description[sl]": "Tema izdelana v slogu Oxygen",
        "Description[sv]": "Tema skapat med Oxygen-stilen",
        "Description[tr]": "Oksijen biçeminde yapılmış tema",
        "Description[uk]": "Тему виконано у стилі Oxygen",
        "Description[x-test]": "xxTheme done in the Oxygen stylexx",
        "EnabledByDefault": true,
        "Id": "oxygen",
        "License": "GPL",
        "Name": "Oxygen",
        "Name[ar]": "أكسجين",
        "Name[es]": "Oxígeno",
        "Name[he]": "חמצן",
        "Name[pa]": "ਆਕਸੀਜਨ",
        "Name[pl]": "Tlen",
        "Name[sk]": "Kyslík",
        "Name[sl]": "Kisik",
        "Name[sr@ijekavian]": "Кисеоник",
        "Name[sr@ijekavianlatin]": "Kiseonik",
        "Name[sr@latin]": "Kiseonik",
        "Name[sr]": "Кисеоник",
        "Name[tr]": "Oksijen",
        "Name[x-test]": "xxOxygenxx",
        "Name[zh_CN]": "Oxygen 轻氧",
        "Version": "@KF6_MIN_VERSION@",
        "Website": "https://www.kde.org/"
    },
    "X-Plasma-API": "5.0"
}
