#ifndef config_liboxygen_h
#define config_liboxygen_h

/* config-liboxygen.h. Generated by cmake from config-liboxygen.h.cmake */

/*************************************************************************
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>    *
 *                                                                       *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *************************************************************************/

/* Define to 1 if you have XCB libraries */
#cmakedefine01 OXYGEN_HAVE_X11

#cmakedefine01 OXYGEN_HAVE_KWAYLAND

#endif
