include(${config})

if(NOT altLighterColor)
   set(altLighterColor ${lighterColor})
endif(NOT altLighterColor)
if(NOT altMediumColor)
   set(altMediumColor ${mediumColor})
endif(NOT altMediumColor)
if(NOT altDarkerColor)
   set(altDarkerColor ${darkerColor})
endif(NOT altDarkerColor)

# Decide the help glyph contrast color from mediumColor brightness.
string(REGEX REPLACE "^#" "" mediumHex "${mediumColor}")
string(SUBSTRING "${mediumHex}" 0 2 mediumRHex)
string(SUBSTRING "${mediumHex}" 2 2 mediumGHex)
string(SUBSTRING "${mediumHex}" 4 2 mediumBHex)
math(EXPR mediumR "0x${mediumRHex}")
math(EXPR mediumG "0x${mediumGHex}")
math(EXPR mediumB "0x${mediumBHex}")
math(EXPR mediumLuma "(${mediumR}*299 + ${mediumG}*587 + ${mediumB}*114) / 1000")
if(mediumLuma GREATER_EQUAL 128)
   set(helpContrastColor "#0d0d0d")
else()
   set(helpContrastColor "#f4f2f4")
endif()

file(READ "${input}" contents)
# Replace placeholder colors with semicolons
string(REPLACE "#ff80ff;" "${lighterColor};" contents "${contents}")
string(REPLACE "#804080;" "${mediumColor};" contents "${contents}")
string(REPLACE "#201020;" "${darkerColor};" contents "${contents}")
string(REPLACE "#c080ff;" "${altLighterColor};" contents "${contents}")
string(REPLACE "#604080;" "${altMediumColor};" contents "${contents}")
string(REPLACE "#181020;" "${altDarkerColor};" contents "${contents}")
string(REPLACE "#f4f2f4;" "${helpContrastColor};" contents "${contents}")
# Replace placeholder colors without semicolons (style attributes)
string(REPLACE "#ff80ff\"" "${lighterColor}\"" contents "${contents}")
string(REPLACE "#804080\"" "${mediumColor}\"" contents "${contents}")
string(REPLACE "#201020\"" "${darkerColor}\"" contents "${contents}")
string(REPLACE "#c080ff\"" "${altLighterColor}\"" contents "${contents}")
string(REPLACE "#604080\"" "${altMediumColor}\"" contents "${contents}")
string(REPLACE "#181020\"" "${altDarkerColor}\"" contents "${contents}")
string(REPLACE "#f4f2f4\"" "${helpContrastColor}\"" contents "${contents}")
file(WRITE "${output}" "${contents}")
