{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "The Oxygen Project",
                "Name[ar]": "مشروع أكسجين",
                "Name[az]": "Oxygen layihəsi",
                "Name[bg]": "Екипът на Oxygen",
                "Name[ca@valencia]": "El projecte Oxygen",
                "Name[ca]": "The Oxygen Project",
                "Name[cs]": "Projekt Oxygen",
                "Name[de]": "Das Oxygen-Projekt",
                "Name[en_GB]": "The Oxygen Project",
                "Name[eo]": "La Projekto Oxygen",
                "Name[es]": "El proyecto Oxygen",
                "Name[eu]": "Oxygen proiektua",
                "Name[fi]": "Oxygen-projekti",
                "Name[fr]": "Le projet « Oxygen »",
                "Name[gl]": "Proxecto Oxygen",
                "Name[he]": "מיזם חמצן",
                "Name[hu]": "Az Oxygen projekt",
                "Name[ia]": "Le projecto Oxigen",
                "Name[it]": "Il progetto Oxygen",
                "Name[ka]": "The Oxygen Project",
                "Name[ko]": "The Oxygen Project",
                "Name[lt]": "Oxygen projektas",
                "Name[lv]": "„Oxygen“ projekts",
                "Name[nl]": "Het project Oxygen",
                "Name[nn]": "Oxygen-prosjektet",
                "Name[pl]": "Projekt Tlenu",
                "Name[pt_BR]": "O projeto Oxygen",
                "Name[ro]": "Proiectul Oxygen",
                "Name[ru]": "Проект Oxygen",
                "Name[sa]": "आक्सीजन परियोजना इति",
                "Name[sl]": "Projekt Oxygen",
                "Name[sv]": "Oxygen-projektet",
                "Name[tr]": "Oksijen Projesi",
                "Name[uk]": "Проєкт Oxygen",
                "Name[zh_CN]": "Oxygen 轻氧项目",
                "Name[zh_TW]": "Oxygen 專案"
            }
        ],
        "Category": "",
        "Description": "A breath of fresh air",
        "EnabledByDefault": true,
        "Id": "air",
        "License": "GPL",
        "Name": "Air",
        "Version": "@KF_VERSION@",
        "Website": "https://plasma.kde.org"
    },
    "X-Plasma-API": "5.0"
}
